'use client';
import {useRef,useState} from 'react';
import {Plus,Minus,Maximize2,MapPinned,Eye,EyeOff,LocateFixed,MousePointer2} from 'lucide-react';
import regions from '../app/regions.json';
import paths from '../public/map-paths.json';
const labels:Record<string,[number,number]>={
'11':[20,100],'12':[20,190],'13':[20,280],'14':[220,190],'15':[220,280],'16':[220,370],'17':[20,370],'18':[220,470],'19':[420,470],'21':[220,100],
'31':[220,650],'32':[420,650],'33':[620,650],'34':[620,740],'35':[820,650],'36':[220,560],'51':[820,740],'52':[1020,650],'53':[1220,740],
'61':[420,100],'62':[420,190],'63':[420,280],'64':[620,190],'65':[620,100],
'71':[820,100],'72':[620,280],'73':[620,470],'74':[820,370],'75':[820,190],'76':[620,370],'81':[1020,370],'82':[1020,190],
'91':[1220,190],'92':[1020,470],'93':[1220,560],'94':[1220,370],'95':[1220,470],'96':[1020,280]};
const islandGroups=[{name:'Sumatera',color:'#27bfa7',prefixes:['1','2']},{name:'Jawa',color:'#e6ae49',prefixes:['3']},{name:'Kalimantan',color:'#49a6ee',prefixes:['6']},{name:'Sulawesi',color:'#aa86ef',prefixes:['7']},{name:'Bali & Nusa Tenggara',color:'#f18770',prefixes:['5']},{name:'Maluku',color:'#62c9e3',prefixes:['8']},{name:'Papua',color:'#91c66d',prefixes:['9']}];
const islandFor=(code:string)=>islandGroups.find(g=>g.prefixes.includes(code[0]))!;
const displayName=(name:string)=>name.replace('Daerah Khusus Ibukota','DKI').replace('Daerah Istimewa','DI').replace('Kepulauan','Kep.');
function lines(name:string){const words=displayName(name).split(' ');const rows:string[]=[''];for(const word of words){if((rows[rows.length-1]+' '+word).trim().length>16)rows.push(word);else rows[rows.length-1]=(rows[rows.length-1]+' '+word).trim();}return rows;}

export default function IndonesiaMap({selected,count,onSelect}:{selected:string;count:(province:string)=>number;onSelect:(province:string)=>void}){
 const [zoom,setZoom]=useState(1),[hover,setHover]=useState(''),[showLabels,setShowLabels]=useState(true);
 const atlas=useRef<HTMLElement>(null);
 const [labelOpacity,setLabelOpacity]=useState(.18);
 const viewport=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 const data=regions.map(p=>({...p,total:count(p.name)})),ranked=[...data].sort((a,b)=>b.total-a.total),peak=Math.max(1,ranked[0].total),total=data.reduce((s,p)=>s+p.total,0),coverage=data.filter(p=>p.total>0).length;
 const focused=hover||selected,focus=data.find(p=>p.name===focused),fmt=(n:number)=>n.toLocaleString('id-ID');
 const color=(n:number)=>!n?'#7890a6':n/peak>.66?'#a4efbc':n/peak>.33?'#4bdcce':'#419eda';
 const point=(p:{lon:number;lat:number})=>[(p.lon-94)*27+20,(7-p.lat)*27+100];
 function reset(){setZoom(1);viewport.current?.scrollTo({left:0,top:0,behavior:'smooth'})}
 return <section ref={atlas} className="atlas atlasPremium panel">
 <div className="atlasHeading"><div><span className="atlasEyebrow">ATLAS PELATIH · INDONESIA</span><h2>Jelajahi persebaran nasional</h2><p>Pilih provinsi untuk menjelajahi kabupaten dan kota.</p></div><div className="atlasMetrics"><div><strong>38</strong><span>Provinsi Indonesia</span></div><div><strong>514</strong><span>Kabupaten / kota</span></div></div></div>
 <div className="atlasToolbar"><div className="atlasMode"><span className="atlasModeIcon"><MapPinned size={17}/></span>Jelajahi wilayah Indonesia</div><div className="atlasControls"><button aria-label={showLabels?'Sembunyikan nama provinsi':'Tampilkan nama provinsi'} aria-pressed={showLabels} onClick={()=>setShowLabels(!showLabels)}>{showLabels?<Eye size={17}/>:<EyeOff size={17}/>}<span>Nama provinsi</span></button><label className="labelIntensity">Label<input aria-label="Kejelasan label provinsi" type="range" min="0.05" max="0.65" step="0.05" value={labelOpacity} onChange={e=>setLabelOpacity(Number(e.target.value))}/></label><button aria-label="Buka atau tutup peta layar penuh" title="Peta layar penuh" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void atlas.current?.requestFullscreen()}}><Maximize2 size={17}/><span>Layar penuh</span></button><div className="zoomGroup"><button aria-label="Perkecil peta" disabled={zoom<=1} onClick={()=>setZoom(Math.max(1,zoom-.25))}><Minus size={17}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Perbesar peta" disabled={zoom>=2.5} onClick={()=>setZoom(Math.min(2.5,zoom+.25))}><Plus size={17}/></button></div><button aria-label="Reset ukuran dan posisi peta" title="Reset ukuran peta" onClick={reset}><Maximize2 size={17}/></button></div></div>
 <div className="atlasStage"><div className="atlasViewport" ref={viewport} onPointerDown={e=>{if(zoom<=1||(e.target as Element).closest('[role=button],[data-province]'))return;drag.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;e.currentTarget.scrollLeft=drag.current.left-(e.clientX-drag.current.x);e.currentTarget.scrollTop=drag.current.top-(e.clientY-drag.current.y)}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}} style={{cursor:zoom>1?'grab':undefined,maxHeight:zoom===1?'none':undefined}}>
 <svg style={{width:`${zoom*100}%`}} viewBox="0 0 1440 820" role="group" aria-label="Peta interaktif 38 provinsi Indonesia">
 <defs><radialGradient id="oceanGlow"><stop stopColor="#193b55"/><stop offset="1" stopColor="#071827"/></radialGradient><linearGradient id="land" x1="0" y1="0" x2="0.8" y2="1"><stop stopColor="#439b71"/><stop offset=".6" stopColor="#287754"/><stop offset="1" stopColor="#19553c"/></linearGradient><pattern id="atlasGrid" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M48 0H0V48" fill="none" stroke="#668fb0" strokeWidth=".5" opacity=".13"/></pattern><filter id="landShadow" x="-20%" y="-20%" width="140%" height="150%"><feDropShadow dx="0" dy="6" stdDeviation="5" floodColor="#020b15" floodOpacity=".8"/></filter><filter id="pinGlow" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="5"/></filter></defs>
 <rect width="1440" height="820" fill="url(#oceanGlow)"/><rect width="1440" height="820" fill="url(#atlasGrid)"/>
 <g transform="translate(20 100) scale(1.285714)" filter="url(#landShadow)">{paths.map((d,i)=><path key={i} d={d} fill="url(#land)" stroke="#6dcc9c" strokeOpacity=".8" strokeWidth=".7"/>)}</g>
 <path d="M30 289H1408" className="equator"/><text x="1310" y="278" className="coordinateLabel">KHATULISTIWA</text>
 <text x="30" y="38" className="oceanLabel">94° BT</text><text x="1290" y="38" className="oceanLabel">141° BT</text><text x="870" y="590" className="seaName">LAUT FLORES</text><text x="400" y="555" className="seaName">LAUT JAWA</text><text x="880" y="80" className="seaName">LAUT SULAWESI</text>
 <g className="compass" transform="translate(1377 110)"><path d="M0 -28L-8 3L0 -3L8 3Z" fill="#acc2d2"/><path d="M0 22L-8 3L0 8L8 3Z" fill="#3a5c76"/><text x="0" y="-38" textAnchor="middle">U</text></g>
 {showLabels&&data.map(p=>{const [lx,ly]=labels[p.code], [px,py]=point(p),active=focused===p.name;return <path key={'line'+p.code} d={`M${px} ${py}L${lx+88} ${ly+27}`} stroke={active?'#f7cd82':'#85b0c7'} strokeWidth={active?2:1} opacity={active?.85:.025} fill="none"/>})}
 {data.map(p=>{const [lx,ly]=labels[p.code],[px,py]=point(p),active=focused===p.name,isSelected=selected===p.name,n=p.total,nameLines=lines(p.name),c=active?'#f7cd82':color(n),radius=7+Math.sqrt(n/peak)*11;return <g key={p.code} role="button" tabIndex={0} aria-label={`${p.name}${isSelected?', dipilih':''}. Pilih provinsi.`} aria-pressed={isSelected} className={`provinceMarker ${active?'isFocused':''}`} onMouseEnter={()=>setHover(p.name)} onMouseLeave={()=>setHover('')} onFocus={()=>setHover(p.name)} onBlur={()=>setHover('')} onClick={()=>onSelect(p.name)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(p.name)}}}>
 <title>{p.name}</title><circle cx={px} cy={py} r={radius+10} fill={c} opacity={active?.3:.13} filter="url(#pinGlow)"/><circle cx={px} cy={py} className="markerHalo" r={radius+8} fill={c} fillOpacity=".06" stroke={c} strokeOpacity={active?.8:.25} strokeWidth="1"/>{isSelected&&<circle className="selectionPulse" cx={px} cy={py} r={radius+10} fill="none" stroke="#f7cd82" strokeWidth="1.5"/>}<circle cx={px} cy={py} r={radius} fill={c} fillOpacity={active?1:.9} stroke={active?'#fff1cf':'#b1e9f1'} strokeWidth={active?2:1}/><circle cx={px} cy={py} r="3" fill="#e5f9ff"/>

 </g>})}
 {showLabels&&data.map(p=>{const [lx,ly]=labels[p.code],active=focused===p.name,n=p.total,nameLines=lines(p.name),c=active?'#f7cd82':islandFor(p.code).color;return <g key={'label'+p.code} data-province={p.code} className={`provinceLabel ${active?'isFocused':''}`} style={{opacity:active?1:labelOpacity}} aria-hidden="true" onMouseEnter={()=>setHover(p.name)} onMouseLeave={()=>setHover('')} onClick={()=>onSelect(p.name)}><rect className="provinceLabelBg" x={lx} y={ly} width="180" height="65" rx="10" fill={active?'#17374b':islandFor(p.code).color} fillOpacity={active?.98:.16} stroke={c} strokeOpacity={active?1:.85}/><rect x={lx+10} y={ly+12} width="3" height="40" rx="1.5" fill={c} opacity={active?1:.65}/><text x={lx+22} y={ly+21} fill={active?'#ffe7b6':islandFor(p.code).color} fontSize="16" fontWeight="600" paintOrder="stroke" stroke="#081f32" strokeWidth="2">{nameLines.map((line,i)=><tspan key={i} x={lx+22} dy={i===0?0:18}>{line}</tspan>)}</text><text x={lx+22} y={ly+55} fill={c} fontSize="14" fontWeight="500" paintOrder="stroke" stroke="#081f32" strokeWidth="2">Wilayah Indonesia</text></g>})}
 </svg></div><div className={`atlasFocusCard ${focus?'hasFocus':''}`} aria-live="polite"><div className="focusIcon">{focus?<LocateFixed size={21}/>:<MousePointer2 size={21}/>}</div><div><span>{selected&&focused===selected?'PROVINSI DIPILIH':focus?'SOROTAN PROVINSI':'JELAJAHI PETA'}</span><strong>{focus?focus.name:'38 provinsi Indonesia'}</strong><small>{focus?'Daftar kabupaten dan kota tersedia di bawah peta':'Sorot penanda atau nama provinsi untuk menjelajahi wilayah'}</small></div></div></div>
 <div className="islandLegend" aria-label="Warna keterangan provinsi menurut kelompok pulau">{islandGroups.map(g=><span key={g.name}><i style={{background:g.color}}/>{g.name}</span>)}</div><div className="islandExplorer"><div className="rankHeading"><span>PROVINSI MENURUT KELOMPOK PULAU</span><small>Pilih provinsi untuk melihat rincian</small></div><div className="islandExplorerGrid">{islandGroups.map(g=><section className="islandGroup" key={g.name} style={{borderTopColor:g.color,background:`color-mix(in srgb, ${g.color} 9%, #10283b)`}}><h3 style={{color:g.color}}><i style={{background:g.color}}/>{g.name}</h3><div>{data.filter(p=>islandFor(p.code).name===g.name).map(p=><button key={p.code} aria-pressed={selected===p.name} className={selected===p.name?'islandProvinceSelected':''} onMouseEnter={()=>setHover(p.name)} onMouseLeave={()=>setHover('')} onFocus={()=>setHover(p.name)} onBlur={()=>setHover('')} onClick={()=>onSelect(p.name)}><span style={{color:g.color}}>{displayName(p.name)}</span></button>)}</div></section>)}</div></div><p className="atlasNote">Peta wilayah terbuka untuk umum. Jumlah, identitas, dan riwayat pelatih tersedia melalui database dengan akses terbatas. Penanda provinsi bersifat indikatif.</p>
 </section>
}
