'use client';
import {useState,useEffect,useRef} from 'react';
import {trainerBreakdown,trainerCategory} from '../lib/trainer-breakdown';
import {Bar,BarChart,CartesianGrid,XAxis,YAxis,Tooltip,Cell} from 'recharts';
import {ChartContainer} from './ui/chart';
import CenterPie from './center-pie';
import {provinceDistribution,formatPercent} from '../lib/trainer-analysis';
import {groupTrainers,type TrainingRecord} from '../lib/trainer-groups';
import regions from '../app/regions.json';
export default function ProvinceDistribution({records,selected,onSelect,label,loading}:{records:TrainingRecord[];selected:string;onSelect:(name:string,category?:string)=>void;label:string;loading:boolean}){
 const [mode,setMode]=useState<'chart'|'table'>('chart'),[focus,setFocus]=useState(selected),[category,setCategory]=useState(''),[namesPage,setNamesPage]=useState(1);
 function openRegion(name:string){setFocus(name);setCategory('');onSelect(name)}
 function openCategory(name:string){setCategory(name);onSelect(focus,name)}
 useEffect(()=>{setFocus(selected);setCategory('');setNamesPage(1)},[selected]);
 const namesRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{setCategory('');setNamesPage(1)},[focus,label]);
 useEffect(()=>{setNamesPage(1);if(category)namesRef.current?.scrollIntoView({behavior:'smooth',block:'start'})},[category]);
 const viewport=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(viewport.current)viewport.current.scrollTop=0},[focus,mode]);
 const distribution=provinceDistribution(records,regions.map(p=>p.name),true);
 const detail=focus?trainerBreakdown(records,focus):null;
 const total=detail?.total??distribution.total,center=distribution.center;
 const items=detail?.items||[...distribution.items].sort((a,b)=>a.name==='Pusat'?-1:b.name==='Pusat'?1:b.count-a.count||a.name.localeCompare(b.name,'id'));
 const categoryPeople=category?groupTrainers(records.filter(r=>r.province===focus)).filter(p=>trainerCategory(p.records,focus)===category):[];
 return <section className="panel distributionPanel" aria-labelledby="distributionTitle">
  <div className="panelTitle"><div><div className="eyebrow">ANALISIS PERSEBARAN</div><h2 id="distributionTitle">{focus?`Rincian pelatih ${focus}`:'Pelatih Pusat dan provinsi'}</h2><p>{label}</p></div><div className="distributionTabs"><button aria-pressed={mode==='chart'} onClick={()=>setMode('chart')}>Grafik</button><button aria-pressed={mode==='table'} onClick={()=>setMode('table')}>Tabel</button></div></div>
  {focus&&<div className="distributionBreadcrumb"><button onClick={()=>{setFocus('');setCategory('');onSelect('')}}>Kembali ke Pusat dan 38 provinsi</button><span>{focus}</span><button onClick={()=>onSelect(focus)}>Lihat daftar pelatih</button></div>}<div className="distributionMetrics"><span><b>{loading?'…':total.toLocaleString('id-ID')}</b> pelatih unik · {focus||'Pusat + 38 provinsi'}</span>{!focus&&<span>Pelatih Pusat: <b>{loading?'…':center.toLocaleString('id-ID')}</b> orang · {formatPercent(total?center/total*100:0)}</span>}</div>
  <p className="distributionNote">{focus?`Persentase dihitung dari ${total.toLocaleString('id-ID')} pelatih unik di ${focus} pada filter aktif. ${focus==='Pusat'?'Empat instansi utama ditampilkan. Instansi lain atau yang belum jelas tetap dipisahkan agar seluruh pelatih terhitung.':'Pelatih Provinsi dipisahkan dari Kabupaten/Kota. Wilayah kosong atau bertentangan tetap berada dalam kelompok perlu verifikasi.'}`:'Klik batang atau nama Pusat/provinsi untuk membuka grafik rincian. Persentase nasional mencakup seluruh pelatih unik Pusat dan daerah pada filter pelatihan, tahun dan tingkat.'}</p>
  {loading?<p role="status" className="distributionEmpty">Memuat persebaran…</p>:!total?<p className="distributionEmpty">Tidak ada pelatih pada pilihan ini. Ubah pilihan pelatihan, tahun atau tingkat.</p>:<>
   {mode==='chart'&&!!focus&&<CenterPie key={`${focus}:${label}`} region={focus} items={items} total={total} onSelect={openCategory}/>}
   {mode==='chart'&&!focus&&<div className="distributionScroll" ref={viewport}><ChartContainer key={`${focus||'national'}:${label}`} config={{count:{label:'Pelatih unik',color:'#258590'}}} className="provinceChart" style={{height:Math.max(220,items.length*34+40),minWidth:focus?780:650,aspectRatio:'auto'}}><BarChart accessibilityLayer data={items} layout="vertical" margin={{top:10,right:155,bottom:10,left:8}}><CartesianGrid horizontal={false} stroke="#e4edef"/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={focus?260:185} tick={({x,y,payload}:any)=><text x={x-8} y={y} textAnchor="end" dominantBaseline="middle" fill="#355566" fontSize={12} role={!focus?'button':undefined} tabIndex={!focus?0:undefined} aria-label={!focus?`Lihat rincian ${payload.value}`:undefined} style={{cursor:!focus?'pointer':'default'}} onClick={()=>{if(!focus)openRegion(payload.value)}} onKeyDown={e=>{if(!focus&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openRegion(payload.value)}}}>{String(payload?.value||'').length>38?String(payload?.value||'').slice(0,36)+'…':String(payload?.value||'')}</text>} tickLine={false} axisLine={false}/><Tooltip cursor={{fill:'#edf6f7'}} content={({active,payload})=>{const item=payload?.[0]?.payload;return active&&item?<div className="distributionTooltip"><b>{item.name}</b><span>{item.count.toLocaleString('id-ID')} orang · {formatPercent(item.percent)}</span></div>:null}}/><Bar onClick={(data:any)=>{const name=data?.payload?.name||data?.name;if(name){if(!focus)openRegion(name);else openCategory(name)}}} style={{cursor:'pointer'}} dataKey="count" fill="#258590" radius={[0,5,5,0]} barSize={18} isAnimationActive={false} label={({x,y,width,height,index}:any)=>{const item=items[index];if(!item)return null;return <text x={Number(x)+Number(width)+10} y={Number(y)+Number(height)/2} dominantBaseline="middle" fill="#355566" fontSize={12}>{item.count.toLocaleString('id-ID')} orang · {formatPercent(item.percent)}</text>}}>{items.map(item=><Cell key={item.name} fill={item.name==='Pusat'?'#c08b32':'#258590'}/>)}</Bar></BarChart></ChartContainer></div>}
   {mode==='table'&&<div className="distributionScroll tableWrap"><table><caption className="sr-only">Jumlah dan persentase pelatih unik Pusat dan 38 provinsi</caption><thead><tr><th>{focus==='Pusat'?'Instansi':focus?'Tingkat / Kabupaten / Kota':'Pusat / Provinsi'}</th><th>Pelatih unik</th><th>Persentase</th></tr></thead><tbody>{items.map(item=><tr key={item.name} className={selected===item.name?'distributionSelected':''}><td><button aria-pressed={selected===item.name} onClick={()=>{if(!focus)openRegion(item.name);else openCategory(item.name)}}>{item.name}</button></td><td>{item.count.toLocaleString('id-ID')} orang</td><td>{formatPercent(item.percent)}</td></tr>)}</tbody><tfoot><tr><th>Total pelatih unik</th><th>{total.toLocaleString('id-ID')} orang</th><th>100,00%</th></tr></tfoot></table></div>}
   {category&&<div className="categoryNames" ref={namesRef} role="region" aria-label={`Daftar pelatih ${category}`}><div className="panelTitle"><div><h3>{category}</h3><p>{categoryPeople.length.toLocaleString('id-ID')} pelatih unik · {label}</p></div><button onClick={()=>{setCategory('');onSelect(focus)}}>Tutup daftar</button></div>{categoryPeople.length?<><div className="tableWrap"><table><thead><tr><th>Nama pelatih</th><th>Instansi</th><th>Jabatan</th><th>Riwayat pada filter aktif</th></tr></thead><tbody>{categoryPeople.slice((namesPage-1)*50,namesPage*50).map(p=><tr key={p.key}><td><b>{p.name}</b></td><td>{p.records[0].institution||'Belum terisi'}</td><td>{p.records[0].job||'Belum terisi'}</td><td>{[...new Set(p.records.map(r=>`${r.training||'Pelatihan'} ${r.year||''}`.trim()))].join('; ')}</td></tr>)}</tbody></table></div><div className="pagination"><span>{(namesPage-1)*50+1}–{Math.min(namesPage*50,categoryPeople.length)} dari {categoryPeople.length} pelatih</span><div><button disabled={namesPage===1} onClick={()=>setNamesPage(namesPage-1)}>Sebelumnya</button><button disabled={namesPage*50>=categoryPeople.length} onClick={()=>setNamesPage(namesPage+1)}>Berikutnya</button></div></div></>:<p className="distributionEmpty">Tidak ada pelatih pada kategori ini untuk filter aktif.</p>}</div>}
   {!focus&&<p className="distributionNote">Pusat ditampilkan paling atas dengan warna emas; provinsi diurutkan dari jumlah terbesar. Semua 38 provinsi ditampilkan, termasuk yang belum memiliki peserta. Klik batang atau nama kategori untuk membuka rinciannya. Pembulatan persentase dapat membuat jumlahnya berbeda sedikit dari 100%.</p>}
  </>}
 </section>
}
