import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapPinned,LockKeyhole} from 'lucide-react';
import IndonesiaMap from './components/indonesia-map';
import regions from './app/regions.json';
import './styles.css';
import './portal.css';
const database='https://persebaran-pelatih-desa.subditkapasitaspemde.chatgpt.site/';
function Portal(){const [selected,setSelected]=useState('');const region=regions.find(p=>p.name===selected);return <main className="portal"><div className="portalTop"><div className="portalBrand"><MapPinned size={32}/><div><strong>SubditPKPD</strong><span>Pengembangan Kapasitas Pemerintahan Desa</span></div></div><a className="accessLink" href={database}><LockKeyhole size={18}/>Buka database</a></div><div className="portalIntro"><div className="eyebrow">DATABASE PELATIH APARATUR DESA</div><h1>Persebaran pelatih Indonesia</h1><p>Jelajahi wilayah Indonesia dan akses database pelatih.</p></div><div className="accessNotice"><LockKeyhole size={25}/><p><strong>Data pelatih memerlukan izin akses.</strong><br/>Selama pemindahan berlangsung, tombol Buka database mengarahkan Anda ke website lama yang masih dilindungi login. Login di alamat baru belum tersedia.</p></div><IndonesiaMap selected={selected} count={()=>0} onSelect={setSelected}/><section className="panel regionDetail"><div className="panelTitle"><h2>{region?region.name:'Kabupaten dan kota'}</h2>{region&&<button onClick={()=>setSelected('')}>Hapus pilihan</button>}</div>{region?<><p>{region.districts.length} kabupaten dan kota di {region.name}. Daftar ini merupakan referensi wilayah, bukan daftar persebaran pelatih.</p><div className="districtGrid">{region.districts.map(d=><span key={d.code}>{d.name}</span>)}</div></>:<p>Pilih provinsi pada peta untuk melihat daftar kabupaten dan kota.</p>}</section><footer className="portalFoot"><span>SubditPKPD · 38 provinsi dan 514 kabupaten/kota.<br/>Peta: superpikar/indonesia-geojson (BAKOSURTANAL). Wilayah: cahyadsn/wilayah, kode Kemendagri 2025.</span><a href={database}>Buka database dengan akses terbatas</a></footer></main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><Portal/></React.StrictMode>);
